FROM onsdigital/java-component

WORKDIR /usr/src

ADD *-jar-with-dependencies.jar target/

CMD java -Xmx4094m                                            \
    -Drestolino.packageprefix=com.github.onsdigital.brian.api \
    -jar target/*-jar-with-dependencies.jar
